version: "3.8"

services:
  flask-app:
    build: .
    ports:
      - "5005:5005"  # Correction du port
    volumes:
      - .:/app  # Monte le répertoire local dans le conteneur
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
